# Generated by Django 5.2.3 on 2025-06-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='reservado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
